services:

  #######################################
  # Docker Socket Proxy: Secure Docker API access
  #######################################
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: portainer-socket-proxy
    restart: unless-stopped
    networks:
      - socket-proxy
    # ports:
    #   - "2375:2375"    # Docker API (debug/info only)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Portainer requires more permissions than Traefik
      # Allow read/write operations
      - POST=1
      # API sections - enabled for Portainer
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=1
      - GRPC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=1
      - TASKS=1
      - VOLUMES=1
      # Container-specific controls
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      # Secrets (keep disabled for security)
      - SECRETS=0
      # Events (needed for real-time updates)
      - EVENTS=1

  #######################################
  # Portainer: Docker Management UI
  #######################################
  portainer:
    image: portainer/portainer-ce:2.33.6
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://socket-proxy:2375
    depends_on:
      - socket-proxy
    networks:
      - socket-proxy
      - default
    ports:
      - "9443:9443"
      # - "8000:8000" # Remove if you do not intend to use Edge Agents
      # - "9000:9000" # If you require HTTP port 9000 open for legacy reasons
    volumes:
      - portainer_data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  portainer_data:

networks:
  socket-proxy:
    name: portainer-socket-proxy
    driver: bridge
    internal: true
