services:

  #######################################
  # Docker Socket Proxy: Secure Docker API access
  #######################################
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: glances-socket-proxy
    restart: unless-stopped
    networks:
      - socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # Glances needs read-only access to containers
      # Deny write operations
      - POST=0
      # API sections - minimal for Glances monitoring
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1          # Required: monitor containers
      - DISTRIBUTION=0
      - EXEC=0
      - GRPC=0
      - IMAGES=1              # Required: list images
      - INFO=1                # Required: Docker info
      - NETWORKS=1            # Required: network stats
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=1              # Required: system info
      - TASKS=0
      - VOLUMES=1             # Required: volume stats
      # Container-specific controls
      - ALLOW_START=0
      - ALLOW_STOP=0
      - ALLOW_RESTARTS=0
      # Secrets (disabled)
      - SECRETS=0
      # Events (needed for real-time updates)
      - EVENTS=1

  #######################################
  # Glances: System monitoring tool
  #######################################
  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    depends_on:
      - socket-proxy
    pid: host
    networks:
      - socket-proxy
      - default
    ports:
      - "61208:61208"    # Web UI
      - "61209:61209"    # API
    volumes:
      # Mount host filesystems for monitoring (read-only)
      - /:/rootfs:ro
      - /etc/os-release:/etc/os-release:ro
    environment:
      - TZ=${TZ:-Europe/Paris}
      - GLANCES_OPT=-w
      - DOCKER_HOST=tcp://socket-proxy:2375

networks:
  socket-proxy:
    name: glances-socket-proxy
    driver: bridge
    internal: true
