services:
  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    container_name: mailcatcher
    ports:
      - "<Docker_bridge_IP or host.docker.internal>:1080:1080"
      - "<Docker_bridge_IP or host.docker.internal>:1025:1025"