services:

  #######################################
  # Konga database prepare
  #######################################
  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - kong-database

  #######################################
  # Konga: Kong GUI
  #######################################
  konga:
    image: pantsel/konga:latest
    restart: unless-stopped
    networks:
        - kong-net   
    environment:
      TOKEN_SECRET: Secret2Login
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_DATABASE: konga
      DB_PASSWORD: ${KONG_PG_PASSWORD:-kong}
      # DB_URI: postgresql://kong:${KONG_PG_PASSWORD:-kong}@kong-database:5432/konga
      NODE_ENV: production
      # BASE_URL: konga.apps.local
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

# volumes:
#   kong_data: {}
  
# networks:
#  kong-net:

