services:

  #######################################
  # NeuVector Enforcer: Non-Privileged Mode
  # Uses capabilities instead of full privileged mode
  # Deploy on nodes where Allinone is NOT running
  #######################################
  enforcer:
    image: neuvector/enforcer:${NEUVECTOR_VERSION:-latest}
    container_name: neuvector-enforcer
    restart: unless-stopped
    pid: host
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - IPC_LOCK
    security_opt:
      - label:disable
      - apparmor:unconfined
      - seccomp:unconfined
    environment:
      - CLUSTER_JOIN_ADDR=${CLUSTER_JOIN_ADDR}
      - NV_PLATFORM_INFO=platform=Docker
    ports:
      - "18301:18301"
      - "18301:18301/udp"
      - "18401:18401"
    volumes:
      - /lib/modules:/lib/modules:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys/fs/cgroup:/host/cgroup:ro
