---
- name: Restart Cockpit service
  ansible.builtin.systemd:
    name: cockpit.socket
    state: restarted

- name: Restart NetworkManager service
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted

- name: Restart Polkit service
  ansible.builtin.systemd:
    name: polkit
    state: restarted
