# Let's Encrypt Production ClusterIssuer
# Use this for production certificates (rate limited)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Production ACME server
    server: https://acme-v02.api.letsencrypt.org/directory

    # Email for certificate expiry notifications
    email: your-email@example.com

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod-account-key

    # HTTP01 challenge solver
    solvers:
      - http01:
          ingress:
            # Use Traefik ingress class
            ingressClassName: traefik
            # Or for older clusters:
            # class: traefik
