# Let's Encrypt Staging ClusterIssuer
# Use this for testing (no rate limits, but untrusted certificates)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Staging ACME server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email for notifications
    email: your-email@example.com

    # Secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging-account-key

    # HTTP01 challenge solver
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
