services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  kong-database:
    image: postgres:15
    container_name: kong-postgres
    restart: always
    networks:
      - kong-net
    user: postgres
    ports:
      - "5432:5432"
    volumes:
      - kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-kongpass}
      POSTGRES_DB: kong
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  #######################################
  # Kong database migration
  #######################################
  kong-migration:
    image: ${KONG_DOCKER_TAG:-kong:3.9.0-ubuntu}
    command: kong migrations bootstrap
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kongpass}
      KONG_PG_USER: kong
      # KONG_PASSWORD: Secret2Login # (Enterprise only): The default password for the admin super user for Kong Gateway.
      
    depends_on:
      - kong-database

  #######################################
  # Kong: The API Gateway
  #######################################
  kong:
    image: ${KONG_DOCKER_TAG:-kong:3.9.0-ubuntu}
    restart: always
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-kongpass}
      # KONG_PROXY_LISTEN: 0.0.0.0:8000
      # KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002,http://localhost:8899,http://manage.kong.apps.local,http://admin.kong.apps.local 
      # KONG_ADMIN_GUI_URL: http://localhost:8002,http://localhost:8899,manage.kong.apps.local,admin.kong.apps.local 
      KONG_LICENSE_DATA:
    ports:
      - "${KONG_INBOUND_PROXY_LISTEN:-0.0.0.0}:8000:8000/tcp"
      - "${KONG_INBOUND_SSL_PROXY_LISTEN:-0.0.0.0}:8443:8443/tcp"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    depends_on:
      - kong-database
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  kong-unofficial-admin-ui:
      image: pocketdigi/kong-admin-ui:0.5.3
      container_name: kong-admin-ui
      networks:
        - kong-net
      ports:
        - "8899:80"

volumes:
  kong_data: {}
  
networks:
 kong-net:
  driver: bridge

