apiVersion: v1
kind: Secret
metadata:
  name: kaniko-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Remplacez par le contenu base64 de votre ~/.docker/config.json :
  # cat ~/.docker/config.json | base64
  # ou via commande CLI :
  # kubectl create secret docker-registry kaniko-registry-secret \
  #   --docker-server=ghcr.io \
  #   --docker-username=<GITHUB_USER> \
  #   --docker-password=<GITHUB_TOKEN> \
  #   --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6e319
