version: '3.8'

services:

  #######################################
  # Docker Socket Proxy: Secure Docker API access
  #######################################
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
    environment:
      # Portainer Swarm requires more permissions
      # Allow read/write operations
      - POST=1
      # API sections - enabled for Portainer Swarm
      - BUILD=0
      - COMMIT=0
      - CONFIGS=1             # Swarm configs
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=1
      - GRPC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1               # Swarm nodes
      - PLUGINS=0
      - SERVICES=1            # Swarm services
      - SESSION=0
      - SWARM=1               # Swarm management
      - SYSTEM=1
      - TASKS=1               # Swarm tasks
      - VOLUMES=1
      # Container-specific controls
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTARTS=1
      # Secrets (enable for Swarm secrets management)
      - SECRETS=1
      # Events (needed for real-time updates)
      - EVENTS=1
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  #######################################
  # Portainer Agent: Communicate with Swarm nodes
  #######################################
  agent:
    image: portainer/agent:lts
    environment:
      - AGENT_CLUSTER_ADDR=tasks.agent
      - DOCKER_HOST=tcp://socket-proxy:2375
    volumes:
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - socket-proxy
    depends_on:
      - socket-proxy
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  #######################################
  # Portainer: Docker Management UI
  #######################################
  portainer:
    image: portainer/portainer-ce:lts
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - socket-proxy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
    attachable: true
  socket-proxy:
    driver: overlay
    internal: true

volumes:
  portainer_data:
