---
# Uptime Kuma role defaults
uptime_kuma_version: "2.5.3"
uptime_kuma_image: "louislam/uptime-kuma:{{ uptime_kuma_version }}"
uptime_kuma_port: 3001
uptime_kuma_domain: "{{ traefik_domain | default('kamitbrains.fr') }}"
uptime_kuma_hostname: "status.{{ uptime_kuma_domain }}"
uptime_kuma_compose_dir: "/opt/uptime-kuma"
uptime_kuma_timezone: "Europe/Paris"
