# Use an official Python runtime as a parent image
FROM python:3.10-slim-bookworm

# Install Node.js and PM2
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g pm2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Installing uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file into the container at /usr/src/app
COPY pyproject.toml uv.lock .python-version ./

# Install any needed packages specified in requirements.txt
RUN uv sync
# RUN ln -s .venv/bin/uvicorn /usr/local/bin/uvicorn

RUN uv pip compile pyproject.toml -o requirements.txt && pip3 install -r requirements.txt

# Make port 80 and 9000 available to the world outside this container
EXPOSE 80 9000

# Set the working directory in the container
WORKDIR /usr/src/app/src

# Run the application using PM2
CMD ["pm2-runtime", "start", "ecosystem.config.js"]
