---
# Stirling-PDF role defaults
stirling_pdf_image: "stirlingtools/stirling-pdf:latest"
stirling_pdf_domain: "kamitbrains.fr"
stirling_pdf_hostname: "stirling.{{ traefik_domain | default(stirling_pdf_domain) }}"
stirling_pdf_alias_hostname: "stirling-pdf.{{ traefik_domain | default(stirling_pdf_domain) }}"
stirling_pdf_short_alias_hostname: "pdf2.{{ traefik_domain | default(stirling_pdf_domain) }}"
stirling_pdf_compose_dir: "/opt/stirling-pdf"
stirling_pdf_container_port: 8080
stirling_pdf_enabled: false

